interlock:
  image: rguo/interlock
  volumes:
    - /var/lib/boot2docker:/etc/docker
  command: --swarm-url=$DOCKER_HOST --swarm-tls-ca-cert=/etc/docker/ca.pem --swarm-tls-cert=/etc/docker/server.pem --swarm-tls-key=/etc/docker/server-key.pem --debug -p aerospike start
  environment:
    - AEROSPIKE_NETWORK_NAME=docker
    - AEROSPIKE_CLUSTER_NAME=aerospike
  net: docker

aerospike:
  image: aerospike/aerospike-server
  volumes:
#    - ./data:/opt/aerospike/data # Maps this system (system that's executing docker-compose) to remote hosts
    - /data:/opt/aerospike/data
    - ./aerospike.conf:/opt/aerospike/etc/aerospike.conf:ro
  volumes_from:
    - aerospike-data
  command: --foreground --config-file /opt/aerospike/etc/aerospike.conf
  labels:
    - "com.aerospike.cluster=aerospike"
  environment:
    - "affinity:com.aerospike.cluster!=aerospike"
  net: docker

aerospike-data:
  image: aerospike/aerospike-server
  entrypoint: tail -f /dev/null
  volumes:
    - /opt/aerospike/shadow
  net: docker
